# 生产环境
spring:
  # 数据源
  datasource:
    # mysql容器网络访问名为db
    url: jdbc:mysql://mysql:3306/studio?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: changlu
    password: b6e6V4EjML
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # 地址  redis的容器网络访问名是redis
    host: redis
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: TB2uKeMi2S
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 上传路径
file:
  upload:
    dir: /tmp/static/  # 文件上传磁盘路径
  visit:
    ip: studio.codercl.xyz   # 访问服务器ip地址。本地测试需要加上项目端口号
    path: /studio/static/   # 访问路径
    protocol: http   # 请求协议

# 第三方服配置
# 阿里云OSS配置
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
    key:

# 上传选项：本地(file) or 第三方服务(aliyun)
uploadOption:
  method: file

# 备份资源和数据库sql
backup:
  sql:
    dataBackupPath: /tmp/static
    host: db
    port: 3306
    username: root
    password: 123456
    dataBaseName: studio
    filename: studio
  static:
    folder: /tmp/static
    zipFile: /tmp/static.zip
