spring:
  # 数据源  cl-manage
  datasource:
    url: jdbc:mysql://localhost:3306/studio?characterEncoding=utf-8&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/zhifengv0.2-dev?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 上传路径
file:
  upload:
    dir: D:\upload\  # 文件上传磁盘路径
  visit:
    ip: 127.0.0.1:8999   # 访问服务器ip地址。本地测试需要加上项目端口号
    path: /profile/   # 访问路径
    protocol: http   # 请求协议

# 第三方服配置
# 阿里云OSS配置
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
    key:

# 上传选项：本地(file) or 第三方服务(aliyun)
uploadOption:
  method: file

# 备份资源和数据库sql
backup:
  sql:
    dataBackupPath: D:\upload
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    dataBaseName: studio-dev
    filename: studio
  static:
    folder: D:\upload
    zipFile: D:\upload\static.zip

